### ISSUE TITLE
sticky helper not found

### ISSUE THREAD

**Issue by jhr007** [brandonhilkert/ember-cli-sticky#1]
Ember doesn't allow components without a dash in their name: 

> Note: Components must have a dash in their name. So blog-post is an acceptable name, but post is not. This prevents clashes with current or future HTML element names, and ensures Ember picks up the components automatically.

http://guides.emberjs.com/v1.12.0/components/defining-a-component/

I renamed the `app/component/sticky.js` to `app/component/ember-sticky.js` and was able to use `{{#ember-sticky}} .... {{/ember-sticky}}`

I didn't really put much thought to renaming it... maybe `sticky-js` , or `e-sticky`

I think you should also rename the sticky.js & stick.hbs files in `addon/` to match up with the component
- [x] rename sticky.js files in the addon folder to reflect name change, consistency
- [x] fix include to updated file name in app/compnents/new-name-sticky.js 
- [x] Update README.md

**Comment by brandonhilkert** [comment]
Updated and it works! Thanks! `sticky-container` is the component name.
