### ISSUE TITLE
Upgrade ember-cli-htmlbars dependency

### ISSUE THREAD

**Issue by dfreeman** [brandonhilkert/ember-cli-sticky#14]
Recent versions of Ember CLI introduced a deprecation for addons that override `init` and fail to call the super implementation.

The most recent release of `ember-cli-htmlbars` [has taken care of this](https://github.com/ember-cli/ember-cli-htmlbars/issues/77), but `ember-cli-sticky` is locked to an older version. Would it be possible to bump the dependency and issue a new release?

**Comment by brandonhilkert** [comment]
I haven't dealt with Ember apps in awhile and don't foresee myself doing so for the immediate future. As a result, it's difficult to keep up with the quickly changing landscape of Ember.js and associated plugins without constant attention.

I'm personally not interested in maintaining this library anymore. Open to suggestions if it's something you'd like to see present in the eco-system.

**Comment by dfreeman** [comment]
Based on the number of monthly downloads, it looks like this is filling a niche in the ecosystem.

Since we're getting value out of it and it's a pretty lightweight addon, we'd be up for taking over maintenance at Salsify. Would you be open to transferring ownership of the Github repo and npm package?

**Comment by brandonhilkert** [comment]
Absolutely. Let me know what account to transfer to.

**Comment by dfreeman** [comment]
Can you transfer the git repo to the `salsify` organization, and then `npm owner add dfreeman ember-cli-sticky` so we'll be able to release?

Thanks!

**Comment by brandonhilkert** [comment]
I've added you an npm owner. A repo can't be transferred to an org I don't have admin rights to.

**Comment by dfreeman** [comment]
Whoops, sorry about that! I'd been assuming it would just email the org admins for confirmation. Can you just transfer to @jredburn instead?

**Comment by brandonhilkert** [comment]
@dfreeman I sent the transfer request to @jredburn

**Comment by dfreeman** [comment]
@brandonhilkert Got it. Thanks!

**Comment by brandonhilkert** [comment]
Awesome. Enjoy! :)
