### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by erichaus** [brandonhilkert/ember-cli-sticky#9]
Hello, I just installed this and then did:

 # templates/index.hbs

```
<main class="main channels container-fluid">
  <div class="row">
    {{#left-page-split}}
      {{#sticky-container}}
      <div class="split-header">
        <h2># home</h2>
      </div>
      {{/sticky-container}}
```

it does not stick.. am I doing something wrong?

I notice in debugger that it has class "sticky"

```
<div id="ember636" class="ember-view sticky">      <div class="split-header">
        <h2># home</h2>
      </div>
</div>
```

**Comment by brandonhilkert** [comment]
That all looks right. Does your page scroll? What version are you using? I have it in production and it's working well.

**Comment by knownasilya** [comment]
Seeing the same issue, and my page scrolls and has the sticky class. Setup fires. Note that my element isn't in view when the page loads.

**Comment by knownasilya** [comment]
Looks like it might be related to this: https://github.com/garand/sticky/issues/118

Maybe the setup needs to happen 'afterRender'?

**Comment by medokin** [comment]
Do you use liquid-fire? It seems that it does not work together.

**Comment by knownasilya** [comment]
Ah, yes that is likely.

**Comment by Blackening999** [comment]
So what's the solution? Do not use liquid-fire? Probably most popular tool in rich UI apps?
